export const REQUEST_CARDS = 'REQUEST_CARDS'
export const RECEIVE_CARDS_SUCCESS = 'RECEIVE_CARDS_SUCCESS'
export const RECEIVE_CARDS_ERROR = 'RECEIVE_CARDS_ERROR'

export const REQUEST_CARD_CREATION = 'REQUEST_CARD_CREATION'
export const RECEIVE_CARD_CREATION_SUCCESS = 'RECEIVE_CARD_CREATION_SUCCESS'
export const RECEIVE_CARD_CREATION_ERROR = 'RECEIVE_CARD_CREATION_ERROR'
