export const REQUEST_CARDS = 'REQUEST_CARDS'
export const RECEIVE_CARDS_SUCCESS = 'RECEIVE_CARDS_SUCCESS'
export const RECEIVE_CARDS_ERROR = 'RECEIVE_CARDS_ERROR'

export const REQUEST_CARD = 'REQUEST_CARD'
export const RECEIVE_CARD_SUCCESS = 'RECEIVE_CARD_SUCCESS'
export const RECEIVE_CARD_ERROR = 'RECEIVE_CARD_ERROR'
